<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rubys Unexceptional Exception Constructor &mdash; TRANSCODE</title>
    <link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="/assets/main.css">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
    <link rel="apple-touch-icon" href="/images/logo.png"/>
    <link href="/feed.xml" rel="alternate" type="application/rss+xml" title="TRANSCODE" />
    <meta name="title" content="Rubys Unexceptional Exception Constructor ">
    <link rel="canonical" href="http://trans.github.com/2012/01/19/rubys-unexceptional-exception-constructor/">
     
           
    <meta property="og:title" content="Rubys Unexceptional Exception Constructor "/>
    <meta property="og:url" content="http://trans.github.com/2012/01/19/rubys-unexceptional-exception-constructor/"/>
    
    
    <meta property="og:site_name" content="TRANSCODE">
</head>
<body>
    
<section class="site-nav">
    <header>
        <nav id="navigation">
            <a class="brand" href="/">
                <img src="/images/logo.png" alt="Inc">
            </a>
            <a href="/" class="home">Blog</a>
            <a href="http://incorporated.sendtoinc.com/">Product</a>
            <a href="https://tabcomputing.com/about/">About</a>
        </nav>
        <nav class="tagline">
            <span>Get a modern blog for your company</span>
            <a href="http://incorporated.sendtoinc.com/" class="btn btn-outline">Learn More</a>
        </nav>
    </header>
</section>


<article>

    <div class="container">
        <header>
            <div class="meta">
                By <address><a rel="author" href="" title="" target="_blank"></a> &mdash;
                <time pubdate datetime="2012-19-January" title="January 19, 2012">January 19, 2012</time>
            </div>
            <h1 class="title">Rubys Unexceptional Exception Constructor</h1>
            
        </header>

        <section>
            <p>You would think after all this time Ruby&#39;s Exception class would be a rather robust and clearly comprehensible class.</p>
<div class="highlight"><pre><code class="ruby language-ruby" data-lang="ruby">  <span class="k">raise</span><span class="p">(</span><span class="n">exception</span> <span class="o">[</span><span class="p">,</span> <span class="n">string</span> <span class="o">[</span><span class="p">,</span> <span class="n">array</span><span class="o">]]</span><span class="p">)</span>
</code></pre></div>
<p>Now lets try something </p>
<div class="highlight"><pre><code class="ruby language-ruby" data-lang="ruby"><span class="k">class</span> <span class="nc">MyError</span> <span class="o">&lt;</span> <span class="no">Exception</span>
  <span class="k">def</span> <span class="nf">initialize</span><span class="p">()</span>
    <span class="k">super</span><span class="p">()</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div><div class="highlight"><pre><code class="ruby language-ruby" data-lang="ruby"><span class="o">&gt;&gt;</span> <span class="k">raise</span> <span class="no">MyError</span>
<span class="ss">MyError</span><span class="p">:</span> <span class="no">MyError</span>
    <span class="n">from</span> <span class="p">(</span><span class="n">irb</span><span class="p">):</span><span class="mi">12</span>
    <span class="n">from</span> <span class="sr">/home/</span><span class="n">trans</span><span class="o">/.</span><span class="n">rbenv</span><span class="o">/</span><span class="n">versions</span><span class="o">/</span><span class="mi">1</span><span class="o">.</span><span class="mi">9</span><span class="o">.</span><span class="mi">3</span><span class="o">-</span><span class="n">rc1</span><span class="o">/</span><span class="n">bin</span><span class="o">/</span><span class="ss">irb</span><span class="p">:</span><span class="mi">12</span><span class="ss">:in</span> <span class="sb">`&lt;main&gt;&#39;</span>
</code></pre></div>
<p>No problem. But now lets try to set the message and the backtrace.</p>
<div class="highlight"><pre><code class="ruby language-ruby" data-lang="ruby"><span class="o">&gt;&gt;</span> <span class="k">raise</span> <span class="no">MyError</span><span class="p">,</span> <span class="s2">&quot;This is an error!&quot;</span>
<span class="ss">ArgumentError</span><span class="p">:</span> <span class="n">wrong</span> <span class="n">number</span> <span class="n">of</span> <span class="n">arguments</span> <span class="p">(</span><span class="mi">1</span> <span class="k">for</span> <span class="mi">0</span><span class="p">)</span>
    <span class="n">from</span> <span class="p">(</span><span class="n">irb</span><span class="p">):</span><span class="mi">8</span><span class="ss">:in</span> <span class="sb">`initialize&#39;</span>
<span class="sb">    from (irb):13:in `</span><span class="n">exception</span><span class="s1">&#39;</span>
<span class="s1">    from (irb):13:in `raise&#39;</span>
</code></pre></div>
<p>Clearly Ruby expects any Exception&#39;s initialize method to handle the message argument. That&#39;s a rather strict contract for something Ruby is letting us override. But okay, let&#39;s take that as a given. Obviously Ruby is routing the #raise call to the exception&#39;s initializer. So then we should that the third <code>array</code> argument would passed along too. Turns out that&#39;s not the case.</p>
<div class="highlight"><pre><code class="ruby language-ruby" data-lang="ruby"><span class="k">class</span> <span class="nc">MyError</span> <span class="o">&lt;</span> <span class="no">Exception</span>
  <span class="k">def</span> <span class="nf">initialize</span><span class="p">(</span><span class="o">*</span><span class="n">args</span><span class="p">)</span>
    <span class="nb">p</span> <span class="n">args</span>
    <span class="k">super</span><span class="p">(</span><span class="o">*</span><span class="n">args</span><span class="p">)</span>
  <span class="k">end</span>
<span class="k">end</span>
</code></pre></div><div class="highlight"><pre><code class="ruby language-ruby" data-lang="ruby"><span class="o">&gt;&gt;</span> <span class="k">raise</span> <span class="no">MyError</span><span class="p">,</span> <span class="s2">&quot;This is an error!&quot;</span><span class="p">,</span> <span class="nb">caller</span>
<span class="o">[</span><span class="s2">&quot;This is an error!&quot;</span><span class="o">]</span>
<span class="ss">RuntimeError</span><span class="p">:</span> <span class="no">This</span> <span class="n">is</span> <span class="n">an</span> <span class="no">Error</span><span class="o">!</span>
    <span class="n">from</span> <span class="p">(</span><span class="n">irb</span><span class="p">):</span><span class="mi">1</span>
    <span class="n">from</span> <span class="sr">/home/</span><span class="n">trans</span><span class="o">/.</span><span class="n">rbenv</span><span class="o">/</span><span class="n">versions</span><span class="o">/</span><span class="mi">1</span><span class="o">.</span><span class="mi">9</span><span class="o">.</span><span class="mi">3</span><span class="o">-</span><span class="n">rc1</span><span class="o">/</span><span class="n">bin</span><span class="o">/</span><span class="ss">irb</span><span class="p">:</span><span class="mi">12</span><span class="ss">:in</span> <span class="sb">`&lt;main&gt;&#39;</span>
</code></pre></div>
<p>Nope. No caller in sight. So where did it go? Turns out Ruby is setting the caller via the error&#39;s <code>#set_backtrace</code> method and doesn&#39;t depend on the initializer to handle it at all. This seems rather odd, since it was keen on letting the initializer handle the message argument, and would blow-up if the class won&#39;t take it.</p>

<p>So the upshot seems to be that we can&#39;t customize an exceptions initializer adn expect <code>#raise</code> to play along.</p>

<p>I actually had another point to make about how things gets even worse. Unfortunately had to take care of other chores and by the time I got back to this blog post (months later) I forgot what these &quot;worse things&quot; were. I think it had something to do with how <code>#message</code> calls <code>#to_s</code> rather then returning the message passed to the initializer. But as said I am not certain now. </p>

<p>My conclusion however is this. I was attempting to make use of an Exception class as something more than a mere container for a string message for the <a href="http://github.com/rubyworks/assay">Assay</a> project. That is when I ran into these oddities which made doing so quite unpleasant. To my dismay I ended up abandoning the approach. I brought some aspects of this up in a <a href="http://bugs.ruby-lang.org/issues/5898">issue report</a>.</p>

<p>For reference, here is the relevant Ruby <a href="https://github.com/ruby/ruby/blob/trunk/eval.c">source code</a>.</p>

            
        </section>

        <footer>
            <address>
               
                <p>Written by <strong><a rel="author" href="https://twitter.com/" title="" target="_blank"></a></strong><br>
                <span class="muted"></span>
                </p>
            </address>

        </footer>

        
    </div>
</article>


<footer class="site-footer">
    <div class="container">
        &copy; 2014 
        
        <nav>
            <a href="http://tabcomputing.com/">Tab Computing</a> &middot;
            <a href="/">Blog</a> &middot;
            <a href="http://incorporated.sendtoinc.com/">Product</a> &middot; 
            <a href="https://tabcomputing.com/about/">About</a>
        </nav>
        
        <nav class="social">
            
                
            <a href="/feed.xml" title="RSS Feed">
                <i class="icon icon-rss black"></i>
            </a>
        </nav>
        <p>Incorporated theme by <a href="https://sendtoinc.com">Inc</a></p>
    </div>
</footer>

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<script src="/assets/main.js"></script>






</body>
</html>
